<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                <img src="/assets/img/admin-avatar.png" width="45px" />
            </div>
            <div class="admin-info">
                <div class="font-strong"> </div><small><?=ucfirst($user->username);?></small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="/admin"><i class="sidebar-item-icon fa fa-tachometer"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
        </ul>

        <?=$popNav;?>
    </div>
</nav>